dist: xenial
language: python

python:
  - 3.7
  - 3.8
  - 3.9

cache: pip

install:
  - pip install -r requirements/test.txt
  - pip install .

script: pytest

after_success:
 - codecov

branches:
    only:
        - master
        - /^v\d+(\.\d+)*$/
